name: cash.beer
favicon: null
layout_spectrum: 1
typography_spectrum: 0.921760008437559
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d4ccc9'
    - '#656565'
    - '#e0ab21'
    - '#bf7900'
    - '#171111'
  brandStrength: 0.5
  lightness: 0.5780852732714266
  saturation: 0.8987043180968612
  rhythmicContrast: 0.6641267575323582
purpose: []
